### ISSUE TITLE
Build doesn't work as descibed in README.md

### ISSUE THREAD

**Issue by knut-forkalsrud** [sinbad/git-lfs-ssh-serve#2]
I'm trying to build git-lfs-ssh-serve to get a feel for it. Being new to Go I immediately run into build problems. I have a fresh install of Go from [golang.org](https://golang.org/doc/install), the Mac OS X Package Installer to be precise. The first attempt produces this:

> `go build`
> methods.go:5:2: cannot find package "github.com/sinbad/git-lfs-ssh-serve/Godeps/_workspace/src/github.com/github/git-lfs/lfs" in any of:
>     /usr/local/go/src/github.com/sinbad/git-lfs-ssh-serve/Godeps/_workspace/src/github.com/github/git-lfs/lfs (from $GOROOT)
>     ($GOPATH not set)
> config.go:6:2: cannot find package "github.com/sinbad/git-lfs-ssh-serve/Godeps/_workspace/src/github.com/mitchellh/go-homedir" in any of:
>     /usr/local/go/src/github.com/sinbad/git-lfs-ssh-serve/Godeps/_workspace/src/github.com/mitchellh/go-homedir (from $GOROOT)
>     ($GOPATH not set)

Next I try to set environment variable GOPATH in creative ways, for example `export GOPATH=${pwd)`, but without luck. It seems there are some very specific assumptions about directory layouts that I can't quite grasp. Something related to "Godeps". A quick read of https://godoc.org/github.com/tools/godep isn't particularly enlightening either. It seems the dependencies are already in Godeps/_workspace, so I shouldn't have to "go get" them. I even start changing the import paths in the source files, but that only makes it worse. For the record my `pwd` throughout this is /Users/knut/opensource/git-lfs-ssh-serve

I'd be grateful if someone in the know could amen the build files or the build instructions to make them more easily reproduced. Alternatively some more specific pointers to "the manual" would be appreciated.

Thanks in advance

**Comment by sinbad** [comment]
Sorry this repo was a test back-end for a PR on git-lfs from over a year ago. That PR didn't go ahead in the end so it's pretty useless now. We may come back to it another time; I'll make this repo private after this message to avoid other people being misled.
